apiVersion: 1

datasources:
  - name: '$${DS_PROMETHEUS}'
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    version: 1
    basicAuth: false
    isDefault: true
    editable: true